[package]
name = "fm"
version = "0.1.0"
authors = ["Sam Saint-Pettersen <s.stpettersen+github@gmail.com>"]

[dependencies]
clioptions = { git = "https://github.com/stpettersens/clioptions.git" }
regex = "0.1"
